### ISSUE TITLE
cant install ?

### ISSUE THREAD

**Issue by bonnebulle** [noppingen/grav-plugin-file_exists#1]
Hey
This plugin can very help the GRAV community, thanks !
I already installed plugin in the past...
I well unarchive the .zip into the plugin folder
![image](https://github.com/noppingen/grav-plugin-file_exists/assets/1598041/f8fe8fd7-3018-499e-9422-655cff1947ba)
But nothing appear into ```/admin/plugins/``` page :(
Maybe a bug ?

**Comment by treminaor** [comment]
@bonnebulle the instructions contain a typo - the folder should be named 'file-exists' NOT 'file_exists'. The folder name much match the .yaml file name in the plugin's folder.
